# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20170908_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
        migrations.AlterModelManagers(
            name='perfil',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='password',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='username',
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='obra',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='core.Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(default='Não Informado', max_length=128),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(default='Não Informado', max_length=128),
        ),
    ]
