# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170908_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='seguindo',
            field=models.ManyToManyField(blank=True, null=True, related_name='seguidores', to='core.Perfil'),
        ),
    ]
