# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='publicacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='envio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='publicacao',
            field=models.DateTimeField(),
        ),
    ]
